### ISSUE TITLE
Twitch API slow

### ISSUE THREAD

**Issue by Bukkalow** [justintv/Twitch-API#311]
Hey

How come the Twitch API is so slow ?
For example if you use:
https://api.twitch.tv/kraken/streams?channel=test_channel

It will output:

    {"streams":[],"_total":0,"_links":{"self":"https://api.twitch.tv/kraken/streams?channel=test_channel&limit=25&offset=0","next":"https://api.twitch.tv/kraken/streams?channel=test_channel&limit=25&offset=25","featured":"https://api.twitch.tv/kraken/streams/featured","summary":"https://api.twitch.tv/kraken/streams/summary","followed":"https://api.twitch.tv/kraken/streams/followed"}}

And when someone goes live. It changes that JSON with all kind of info of the stream.
However, this takes about 1-3 minutes to update after a person goes live.
Is there any way this could be almost instantly as a feature update ?
This would make notifications way more real-time

**Comment by Fugiman** [comment]
The reason it takes a few minutes to update the data is due to [caching](http://en.wikipedia.org/wiki/Web_cache). Caching is essential in allowing us to serve the volume of requests the API gets, and isn't something we can easily remove or reduce. At this time there's no way to get this data any faster than once a minute.
