### ISSUE TITLE
Sorry, we were unable to connect to chat. Reconnecting in 2 seconds.

### ISSUE THREAD

**Issue by deadsightsx** [justintv/Twitch-API#324]
Really? why does globals exist? some streamers ask us to spam and you ban us for 8 HOURS!? really are you so inconsiderate that you ban us for that long? holy crap dude get your head out of your butt!

**Comment by scagood** [comment]
Urm what are you asking here, you could not connect to the server initally I assume ao a logical step would be to wait two seconds and try again. Where does that 8 hour ban come from? What do you need to spam for?

You get banned if you go over the 20 chat line per 30 seconds (1.5 seconds per line) if that is what got you banned?

Can you try to elaborate on your problem a bit?

**Comment by BoomLiam** [comment]
It's a fair enough suspension. If you're sending more than 20 lines of chat in 30 seconds (or 100 in 30 for moderators) then you're not doing that accidentally, it's intentional 'spam' and as such, you're locked out of chat for a period of time. This is done to combat bots and users which may fill up an entire chat. Sometimes false positives are caught and users who script a bot badly or a cat walks across their keyboard are caught, but really, an 8 hour suspension isn't bad. Just sleep through it.

**Comment by youssefdetovernickr** [comment]
To be fair though, it's pretty harsh that spamming bans you for 8 hours. A 1 hour ban seems to be even more reasonable. Or make it so the first time you spam isn't as harsh as the next time

**Comment by scagood** [comment]
You have some good suggestions but i feel that the 8 hours bans are justified because it is clearly stated in the documentation [IRC.md](https://github.com/justintv/Twitch-API/blob/master/IRC.md#command--message-limit) and your program should be written to avoid these set bounds (and in most cases can easily be tweaked slightly to comply)

**Comment by PeterAlfonsLoch** [comment]
Its stupid! I get blocked with my broadcaster account for trying some bot commands on my OWN CHANNEL for 8 hours? thats just stupid I should be allowed to do on my channel what I want I now have trouble moderating the channel -.-

**Comment by BoomLiam** [comment]
This lockout has since been reduced to a 2 hour lockout, the limit for moderators is 100 messages in 30 seconds. This limit will NOT be reached accidentally, unless you clearly are spamming in chat.

**Comment by PeterAlfonsLoch** [comment]
2 hours is way to long... especially as a brodcaster account i am directing the stream and lost control!

Am 29. August 2015 um 19:15 schrieb BoomLiam <notifications@github.com>:

This lockout has since been reduced to a 2 hour lockout, the limit for moderators is 100 messages in 30 seconds. This limit will NOT be reached accidentally, unless you clearly are spamming in chat.

**Comment by PeterAlfonsLoch** [comment]
I get that server load shit, but 30 minutes or 1 hour would be enough aölso blocking an Ip instead of a user would also be much nicer oh and a message on why they cant write would also help

**Comment by TournyMasterBotCurse** [comment]
1. You should not be testing in such a way that it is possible to send 100 messages in 30 seconds
2. You should not be testing using a live account

If you've properly modded your bot, you are doing something VERY wrong if you're hitting 100 messages in 30 seconds. Use a rate limit queue because bot commands won't even come close to hitting the cap even in huge channels like riot games or lirik, or even forsenlol.

**Comment by PeterAlfonsLoch** [comment]
Now got blocked for really no appearant reason -.- send 2 messages in 30 second intervall and got blocked!

The bot was not the account but myself it was on purpse but now it happened while i watched my favorite streamer! I id NOT spam or misuse the chat! Its getting silly!

**Comment by Defman21** [comment]
Maybe the moderators of your favorite streamer banned you?

**Comment by youssefdetovernickr** [comment]
Did somebody figure out how bots actually work around this limit, as I'm pretty sure some bots send more than 100 messages in 30 seconds for a lot of channels (not per channel).

**Comment by BoomLiam** [comment]
They are given an exception from Twitch Staff

**Comment by TournyMasterBotCurse** [comment]
That is not accurate.

**Comment by BarryCarlyon** [comment]
@BoomLiam thats incorrect… No one has an Exception

@deadsightsx Sure if a caster asks you to Spam thats fine, but that means you still have to stick to the TOS and the overall chat rules, aka, Spam to a limit that doesn't get you kicked from Twitch.

**Comment by scagood** [comment]
@youssefdetovernickr They use multiple connections to get over that

**Comment by swarley1998** [comment]
i was watching a small streamer today, and he told people to spam chat in order to enter a give away, i spammed chat and got an 8 hour ban, how does that seem even remotely fair?? i got an 8 hour ban because i did what the streamer said to do, it should be up to the streamer and thier mods to figure out who gets punishment or not.

**Comment by nibogd** [comment]
i was banned for trying to install arch in @twitchinstalls :sob:

**Comment by BoomLiam** [comment]
@nibogd Yep, that is the purpose of the system. To stop spam. This system is automatic and lifts in 2 hours.

**Comment by nibogd** [comment]
@BoomLiam thanks, i'll wait two hours... But everybody spams on that channel...

**Comment by Fugiman** [comment]
As it has been mentioned earlier in this thread, the global lockout is a mechanism to prevent the system from falling over due to a few overzealous users and is unlikely to be removed.

**Comment by nibogd** [comment]
But anyway, maybe it's better to throw "you were banned" message instead of "Sorry, we were unable to connect to chat. "? It's hard to figure out what happened.

**Comment by fuckyoui** [comment]
Fuck you

**Comment by minecraftprank** [comment]
I was littaraly playing a TwitchPlaysPokémon-game on Twitch and i litterly got banned because of spammin "A" while no-one said anything

This rly sucks
