### ISSUE TITLE
Why do you not support iframe embeds for recorded videos?

### ISSUE THREAD

**Issue by nextgenthemes** [justintv/Twitch-API#332]
Would make lives easier. I like to drop `<object>`.

**Comment by scien** [comment]
+1

**Comment by bashtech** [comment]
The new player will support this soon: https://www.reddit.com/r/Twitch/comments/3n4q0s/embedding_html5_player_into_site/

**Comment by scien** [comment]
hey @bashtech - that thread only comments on embedding live channels with the new html5 player. this thread is about pre-recorded videos. is there another reddit thread that discusses that? Is it currently possible but not documented? right now pre-recorded content can be played at all on mobile because it's only available with the flash player

**Comment by scien** [comment]
ah, nvm. i guess it will work like this

`channel={channel_name}&video={v12345678}`

**Comment by bashtech** [comment]
Yep, note Flash will be still be required until some time in Q2 of next year and right now there is a cross-domain bug preventing the iframe from working but that should be fixed today.

**Comment by scien** [comment]
any chance this will come with a javascript api? would be nice to be able to programmatically toggle mute, change volume, hide controls, etc. without having to reload an iframe

**Comment by mgleed** [comment]
@bashtech After the iframe fix you mentioned, is there now iframe code you can use now for embedding pre-recorded videos, similar to the iframes available for livestreams, chats, etc.? I didn't see any documentation of it on embedding.md.

**Comment by bashtech** [comment]
@mgleed As mentioned earlier in this thread: `http://player.twitch.tv/?video={video ID}`

Make sure you include the v, b, or c identifier at the beginning of the ID. Ex: http://player.twitch.tv/?video=v19502959

**Comment by mgleed** [comment]
Got it. Sorry, I deleted my comment when I figured out not to include `channel={channel_name}` Thanks for the help, glad this is working.

**Comment by jasongornall** [comment]
+1

**Comment by SJAnderson** [comment]
+1

**Comment by Fugiman** [comment]
This should be supported now. https://github.com/justintv/Twitch-API/blob/master/embed-video.md

**Comment by nextgenthemes** [comment]
@Fugiman how about documenting it  before rushing for a close?

This issue is about **recorded** videos. From trail and error and from that the embed codes on twitch spit out I found out 3 types of urls.

With `/v/`, `/c/`, `/b/` in it. The docs you linked only speak of `v` prefixed video IDs. The URLs containing `/b/` seem to have a id in the embed codes with `a` prefix. For `c` and `v` the prefix seems to reflect what is in the URLs. This should be documented.

Its also not obvious to me what this letters actually mean.

I am working of a wordpress plugin that generates embeds based on twitch URLs, Not extensively tested it but if the above is correct I think I am ready do drop `<object>` and use `<iframe>` for everything and its indeed supported but not documented.

https://github.com/nextgenthemes/advanced-responsive-video-embedder/blob/beta/includes/class-arve-shared.php#L57

https://github.com/nextgenthemes/advanced-responsive-video-embedder/blob/beta/public/class-arve-public.php#L487-L534

**Comment by caeleel** [comment]
@nextgenthemes that is a good point but the documentation is actually complete, because we only support /v type video ids going forward in the new video embed. Both /b and /c type videos are deprecated, and are not guaranteed to work super well with the new embed.

All new videos being created and videos created in the past few months are all /v. We are slowly going through a process of converting /b and /c videos into /v videos.

If you want to know what the prefixes mean, /b and /c are videos stored in FLV format, while /v videos are stored in HLS format (the same format as our live content). /b is for past broadcasts and /c is for highlights. /v has no distinction between past broadcasts and highlights.

Let me know if you have any more questions regarding the embed or videos in general.

**Comment by blueridger** [comment]
> We are slowly going through a process of converting /b and /c videos into /v videos.

Is this completed by now? If I only have the numeric part of a video ID, can I safely assume the prefix is `v` and safely append it blindly?

**Comment by 3ventic** [comment]
That should be safe to do now.

This repository isn't used anymore and discussions should be had at discuss.dev.twitch.tv instead.
