### ISSUE TITLE
Get multiple streams JSON data from twitch API

### ISSUE THREAD

**Issue by FincherFincher** [justintv/Twitch-API#395]
There are two json calls and the call #2 is working. I don't have any idea about the first one (multiple streams). Yes im beginner.

(I know some of you would say: "go and read the docs right there", but it didn't help me very much. https://github.com/justintv/Twitch-API/blob/master/v2_resources/streams.md)

Call #1:

$.getJSON("https://api.twitch.tv/kraken/streams?channel=viagamehs,starladder1.json?callback=", function(response){
    response = JSON.stringify(response);
    OBjonline = jQuery.parseJSON(response);
    alert(response);
});    
Call #2:

$.getJSON("https://api.twitch.tv/kraken/streams/viagamehs_ru.json?callback=?", function(response){
    response = JSON.stringify(response);
    OBjonline = jQuery.parseJSON(response);
    alert(response);

**Comment by scagood** [comment]
The problem lies in the request not in the script the 'callback=?' In your second request should be url encoded but as your first request works fine without a callback I would say just don't use it.

So if his works:
Call #1:
```
$.getJSON(
    "https://api.twitch.tv/kraken/streams?channel=viagamehs,starladder1.json",
    function(response){
        response = JSON.stringify(response);
        alert(response);
    }
);
```

Then this should:
Call #2:
```
$.getJSON(
    "https://api.twitch.tv/kraken/streams/viagamehs_ru.json",
    function(response){
        response = JSON.stringify(response);
        alert(response);
    }
);
```

If this does not worked then I cannot help :smile:

Hope this helps
scagood

**Comment by MrBeardy** [comment]
*callback=?* is a query parameter, and since you're already initiating the query string with *?channel=* in the first URL, you need to use *&* instead of *?* for additional query parameters.

Also, you're adding *.json* onto the end of the '?channel' query parameter. *.json* should be used as the extension for the API URL, the correct URL should be: "https://api.twitch.tv/kraken/streams.json?channel=viagamehs,starladder1&callback=?"

**Comment by FincherFincher** [comment]
@MrBeardy thank you very much! You save my lifetime! gr8 resolution!
