### ISSUE TITLE
Stream Search API not returning results 

### ISSUE THREAD

**Issue by BrianSipple** [justintv/Twitch-API#399]
I haven't been able to test the full API completely, so I don't know this issue's full breadth, but it appears that the Search API is currently broken for streams. The example listed directly in the docs...

```
https://api.twitch.tv/kraken/search/streams?q=starcraft
```

... returns an empty result array. 

Channel search appears to be fine, as does games search, but I have an app that depends on using the stream search and every query that worked last night is now returning no results.

**Comment by TournyMasterBotCurse** [comment]
@BrianSipple You should use the full game name, but /search/streams is not a valid url.

You want /channels?q=starcraft

**Comment by BrianSipple** [comment]
That was pasted directly from the [current example in the docs](https://github.com/justintv/Twitch-API/blob/master/v3_resources/search.md#get-searchstreams)

**Comment by TournyMasterBotCurse** [comment]
Yep, that looks broken :P

**Comment by BrianSipple** [comment]
I'm seeing results again with the original example I posted. However, the some of the queries I was using previously don't appear to be returning identical results when the "limit" parameter is used. 

For example, try https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=6. It returns a results object that reports 170 total items and provides the necessary links for future api calls. However, the "streams" array that would normally hold 6 results after the first call only holds 4. Future requests with the provided links seem to return a similarly truncated "streams" array as well.

**Comment by cgwic** [comment]
currenly 
```
get https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=6
```
returns six for me

**Comment by BrianSipple** [comment]
Nice -- same here. As far as I can tell, everything is back to normal.

**Comment by Pyyric** [comment]
I don't think /search/streams is returning all possible results anymore. Just calling it raw and searching for streams in the twitch.tv/directory it doesn't find them.

**Comment by BrianSipple** [comment]
I've been using the queried route for some time now without noticing any particular issues. Seeing though, there haven't been any more identical cases mentioned here or linked elsewhere, I'm going to go ahead and close this.

**Comment by burakkurkcu** [comment]
This problem seems to exist still.

With _total parameter response shows there is ~100 streams as I search now, which is much more than I need to limit.

`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=6` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=6) 6 streams.
`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=7` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=7) 6 streams.
`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=12` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=12) 9 streams.
`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=16` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=16) 14 streams.
`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=18` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=18) 16 streams.

I only managed to get the correct count of streams as a response to limit <= 6.
