### ISSUE TITLE
CAP LS and CAP LIST commands not supported

### ISSUE THREAD

**Issue by seschwar** [justintv/Twitch-API#405]
`IRC.md` states:

> Using IRCv3 capability registration, it is possible to register for Twitch-specific capabilities.

`CAP LS` and `CAP LIST` are part of the capability negotiation as specified for IRCv3:

> The client should send an LS subcommand with no other arguments to solicit a list of all capabilities.

Certain clients like WeeChat check the available capabilities before enabling them. Twitch not fully implementing IRCv3 capability negotiation breaks regular enabling of capabilities for these clients.

**Comment by kaniini** [comment]
`CAP LS` is indeed required for IRCv3 compliance, also please stop referring to Twitch-specific capabilities as "IRCv3 capabilities".  Thanks.

**Comment by prawnsalad** [comment]
Just to add in, we at kiwiirc.com get a lot of users asking why the user list is now empty. We can't enable the needed capability without checking it exists via CAP LS first.

**Comment by Fugiman** [comment]
This feature is now implemented

**Comment by TingPing** [comment]
Should also handle `CAP END` and when it is not handled your syntax for the invalid command is wrong: `:tmi.twitch.tv 410 :Invalid CAP command`

The syntax should be `:tmi.twitch.tv 410 * END :Invalid CAP command` according to the docs:

>If a client sends a subcommand which is not in the list above or otherwise issues an invalid command, then numeric 410 (ERR_INVALIDCAPCMD) should be sent. The first parameter after the client identifier (usually nickname) should be the commandname; the second parameter should be a human-readable description of the error.

**Comment by kaniini** [comment]
@Fugiman see above please, `CAP END` must be implemented too.

**Comment by Fugiman** [comment]
@prawnsalad @TingPing @kaniini Is `CAP END` causing clients to be unable to connect? If so, which ones?

**Comment by kaniini** [comment]
@Fugiman it is undefined behaviour, and is required by all relevant specifications, please implement both changes

**Comment by jwheare** [comment]
@Fugiman a client conforming to the spec will send CAP END to complete the negotiation, resulting in the "Invalid CAP command" appearing on every connection attempt. Not a great user experience.

The spec actually dictates that negotiation is not supposed to complete until CAP END is sent, i.e. the server should wait for it after sending CAP ACK and not just continue with connection registration.

**Comment by Fugiman** [comment]
>The client MUST be able to use the CAP command anytime, even after registration.
> http://ircv3.net/specs/core/capability-negotiation-3.1.html

We don't care when you send the CAP commands, so we don't stop registration for it. The spec seems to contradictory on this matter. How can we force a client to send `CAP END` when some clients don't support CAP at all? Really the only point of `CAP END` seems to be to imitate `CAP REQ <nothing>`, which tells the server "Hey I understand CAP and don't want anything, so don't give me your legacy defaults". And since we don't have legacy defaults, even that is worthless.

So yeah, for now we don't support CAP END which means a slightly poor UX and that we don't technically follow spec. Due to it not breaking anything it's been filed as a low priority feature request.

Let me know if my understanding of this is wrong, I'd appreciate a better explanation of the spec :)

**Comment by kaniini** [comment]
@Fugiman 

If a client begins capability negotiation it will send `CAP END` to signal that it has finished capability negotiation, this is a required command and the only thing it does is provide a barrier-like construct in the protocol so that you can have old protocol and then everything after is guaranteed to be whatever you negotiated.  If you aren't going to follow the spec, then please stop referring to the TMI service as IRC (or especially IRCv3) as it isn't.

Even after a client finishes registration and *re-enters* capability negotiation, the stream of events from the stream of events from the IRC server, ideally, shouldn't change until the new negotiation result is committed using `CAP END`.

For the record I am the person who edited the IRCv3.1 spec so I would argue I am pretty qualified on how to interpret its meaning.  If you wish for a more formal interpretation, you can of course, open an issue on the [IRCv3 specifications tracker](http://github.com/ircv3/ircv3-specifications/issues), but I feel that the current editorial team will agree with my interpretation :)

**Comment by jwheare** [comment]
> We don't care when you send the CAP commands, so we don't stop registration for it.

Yes you can accept CAP negotiation at any point, however *if* it's initiated by the client before or during registration, you must suspend registration.

> How can we force a client to send CAP END when some clients don't support CAP at all?

Clients that don't support CAP will not initiate CAP negotiation, in which case you don't force anything, you just carry on with registration, no CAP END necessary. CAP END is only necessary if the client initiates CAP negotiation.

> Really the only point of CAP END seems to be to imitate CAP REQ <nothing>

Actually CAP END is required even if you do request something. After the server sends ACK after REQ, it must still wait for CAP END to continue with registration. This mechanism exists to allow other things that may happen after a CAP has been requested, e.g. SASL authentication, though it is not limited to SASL. The behaviour is flexible enough to support *any* further registration stage handshake.

> So yeah, for now we don't support CAP END which means a slightly poor UX and that we don't technically follow spec. Due to it not breaking anything it's been filed as a low priority feature request.

I'm not asking you to follow the spec for the sake of it. There are reasons for it, and conforming clients will expect specific behaviour from conforming servers.

A general purpose client that needs to connect to any number of IRC servers cannot know in advance which CAPs will be available or not, so the best approach is to always do the full handshake, including a CAP LS at the start, and a CAP END at the end. By not supporting *all* of these commands and just doing the minimum that works for you, you're creating errors for no reason, and undermining the advantages of IRC as an open platform and protocol.

That's your prerogative, and fair enough if this issue is a minor priority (I understand there are always more important things to do), but bear in mind that it's somewhat alienating towards IRC client developers.

**Comment by kaniini** [comment]
@jwheare 

I don't think highlighting SASL's use of the negotiation lock is a good example of why CAP END is necessary, it's really meant to be more of a barrier between old and new (i.e. whatever you negotiated) protocol formats.  CAP END predates the SASL binding.

**Comment by TingPing** [comment]
I don't think there would be any harm in END just being a no-op? There is no point in half-assing the spec, it's not hard to just accept valid inputs and return the correct numerics.
