### ISSUE TITLE
Multiple Streams

### ISSUE THREAD

**Issue by anticeraphim** [justintv/Twitch-API#408]
The code works great. I was able to figure out how to adjust the quality of the stream as well. I'm stuck on how the code would workout if I wanted to pull multiple streams. Specifically, I want to have a list of streamers (maybe a part of a twitch team or not) that broadcast on the website, similar to multitwitch. I'd also like it to "feature" the channel w/ the most viewers.

I currently just have our main channel featured on the website, check it out www.opnoobs.com

**Comment by appleseedexm** [comment]
May we have a little more information on this? It should be no problem to request multiple streams from multiple users (one after another) from the API and show whichever you want. 

If you request a new feature to pass multiple users/channels in one request to receive all of them, I don't really see why this should be implemented into the API, since you can already do that (as explained above) with a little bit of extra code.
