### ISSUE TITLE
Inconsistency in channel api

### ISSUE THREAD

**Issue by 2insanepeople** [justintv/Twitch-API#419]
I was working with the api a bit in python when I noticed that mature returned null when false and partner returned false when false. Both return true when true. Seeing as these should both be Boolean values, I am curious the reason for this inconsistency. I also thought I would being this to attention, as it could confuse some people while working with the API.

**Comment by TournyMasterBotCurse** [comment]
(Taking a guess since both null and false can be set)

The broadcaster has probably never set the mature value, it's a nullable bool so it probably means

Null: Never set (interpreted as false)
False: Set at least once, and is currently not enabled
True: Is mature channel.

**Comment by appleseedexm** [comment]
Even if that would be the case, I agree with 2insanepeople. A boolean has a fixed set of values to return (true/false) and null is none of them. Since a channel should always be one of these two (mature/nonmature), null should IMO be defaulted to false. I think that is the same behaviour like on twitch.tv.

**Comment by TournyMasterBotCurse** [comment]
I disagree, nullable booleans are a thing, and knowing whether or not somebody intentionally set a flag is useful information. Defaulting your local code to say null = false for a specific variable is trivial.

**Comment by appleseedexm** [comment]
A boolean = null is bad programming style. And probably there is a reason why major programming languages do not allow this. Of course, you _can_ do it, that doesn't make it nice. If you want to provide three states, don't use a boolean or use a boolean and a supporting variable to state if it was ever defined or not.

**Comment by Myrathi** [comment]
Major programming languages do allow this: it's called a Nullable (or Optional) type/primitive. Null basically infers that is currently "unset." It's an acceptable value and an entirely valid programming style.

**Comment by appleseedexm** [comment]
They allow it - and some of them crash really hard. It might also be 'acceptable', but it is not nice and IMO not good practice. And obviously, someone run into it. I'm also not sure if it is documented, because obviously everyone using it must implement a NULL check. 

Setting something =NULL on purpose is just not nice, and also hard to control, especially in an API situation. And with a boolean it gets even worse, since it should by its definition return only one out of two possible results. (If you're interested, read about the 'Billion Dollar Mistake' by the inventor of NULL, Tony Hoare)

**Comment by freaktechnik** [comment]
So far I'm still convinced that the use of a nullable bool here is the optimal solution from an API design standpoint. And I also want to point out, that the main README of this repository says:
> Blank fields are included as null instead of being omitted.

Further what you think is good or bad practice is very subjective and honestly doesn't apply to everybody. That's why you have code guidelines in projects, so everybody does it the same. And APIs each have their own guidelines.

Documentation "issues" aside, I'm interested why avoiding nullable bools would be better.
From my current understanding fields are null, as long as there is no explicitly specified value for it. Now, twitch sometimes assumes a default value, which might give a disconnect between the value the user thought he set the setting to and what the API reflects (option not checked vs. not set).
But especially in case of the `mature` field it is valuable to know if the user hasn't set it at all, since you are not forced to set a value when signing up or when starting your first stream, i.e. a streamer could have no knowledge of the existence of this setting.

If you'd now developed an application made for children, that would only show them streams that are save for their age (ranking of the game + `mature` field) it is of great interest to be more protective than allowing (this is not a comment on how parenting works these days btw. but just on what would be expected of such an application). This means asking for explicit approval by the parent if the streamer hasn't set the `mature` field, since he could still be using language that parents don't want their child to hear (again - there are arguments about parenting to make here, which I wont).

The alternative to having a nullable value would be to have an object like the following for each optional value (as in, users don't have to explicitly specify a value) in the API:
```js
{
  "value": "<value goes here>",
  "isSet": true
}
```

Am I missing something here? I think having a nullable value is way easier to handle in most languages (depending on their JSON interpretation, of course) than to have such an expanded object. I guess there would be the option of omitting fields, as the documentation mentions, which is probably the best alternative.

**Comment by TournyMasterBotCurse** [comment]
Github needs an upvote feature, @freaktechnik gets a +1 for that explanation, and excellent example. And with regards to the 'isSet' option, that would be a lot of needless data + processing on both the server and consumers part if done for each different available (nullable) data point (since each one would now have two fields instead of one).

**Comment by appleseedexm** [comment]
I totally agree that this is a subjective topic, I apologize if anyone got a different impression of me than just getting my opinion across. 
I think we're kinda running in circles. I get your point and I also know why there are guidelines, architects and designers which define such behavior.
I must add that now I think it is even arguable if you want to provide the fact that the value is set, since you set null = false anyway, but that is another topic (and probably an endless one). 
Additionally, you would not have to return an object, but you could, and depending on the API you could also make distinctive calls depending on which data you want - for most users it would not be relevant if you ever set the value, so requesting the whole object would not be the way to go. 

But either way, it is not my API, and for the sake of this discussion, I think someone should just close it and make sure that the current approach is documented properly ;-)

@TournyMasterBotCurse There is almost never a 'perfect' solution to a requirement, especially in large scale applications. You'll always have some kind of trade off, with every approach you take.
