### ISSUE TITLE
Limit and offset parameters weird behavior

### ISSUE THREAD

**Issue by tomtoump** [justintv/Twitch-API#504]
`limit=1&offset=0` [returns 1 object](https://api.twitch.tv/kraken/channels/esl_csgo/videos?limit=1&offset=0) as expected
`limit=1&offset=1` [returns 2 objects](https://api.twitch.tv/kraken/channels/esl_csgo/videos?limit=1&offset=1)

It's like the limit is set to the sum of limit and offset, and offset is always 0. 
This happens in any endpoint with paginated results.

**Comment by Fugiman** [comment]
> This happens in any endpoint with paginated results.

As far as I can tell it only happens on the `/kraken/channels/:channel/videos` endpoint. If you have an example of it affecting other endpoints please let me know.

Meanwhile I'll investigate why it's happening on the videos endpoint. Thanks!

**Comment by 3ventic** [comment]
I didn't notice it happening on any other endpoints when I checked it yesterday.

**Comment by tomtoump** [comment]
I was wrong. It doesn't happen on any endpoint, but only those related to videos. Apart from `/channels/:channel/videos`,  `/videos/top` and `/videos/followed` are also affected.

**Comment by fonsleenaars** [comment]
Seems to be fixed now.

**Comment by burakkurkcu** [comment]
This problem seems to exist still. 

With _total parameter response shows there is ~100 streams as I search now, which is much more than I need to limit.
 
`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=6` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=6) 6 streams.
`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=7` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=7) 6 streams.
`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=12` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=12) 9 streams.
`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=16` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=16) 14 streams.
`https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=18` [returns](https://api.twitch.tv/kraken/search/streams?q=starcraft&limit=18) 16 streams.

I managed to get the correct count of streams as a response to limit <= 6.

**Comment by tomtoump** [comment]
The pagination issue seems indeed fixed, but the `_total` is the number of videos returned from the current query instead of the expected total videos of the channel.

**Comment by GolfinG** [comment]
@tomtoump @Fugiman I just fixed the bug where `_total` points to the number of videos returned from the current query. It should be working now
