### ISSUE TITLE
Friends API spec release

### ISSUE THREAD

**Issue by mavrick** [justintv/Twitch-API#545]
Any ETA lads?

Cheers,

Mav

**Comment by Fugiman** [comment]
It's still in beta...

**Comment by AlcaDesign** [comment]
Spoilers: not everything is part of Kraken or is beta and is subject to change from Twitch without notice.

Here's what I know from testing:

# List of friends

**URL:** https://api.twitch.tv/kraken/users/:user/friends

**Method:** GET

**Authenticated:** true

**Options:**
- *limit*: int, max length of array up to 100, default 25
- *cursor*: int, data offset timestamp in ns
- *offset*: int, data offset, default 0
- *direction*: string, ''DESC" or "ASC", default "DESC"

**Schema:**
```javascript
{
    _total: <int>,
    _cursor: <'timestamp in ns'>,
    _links: {
        self: <'url'>,
        next: <'url'>
    },
    friends: [
        {
            created_at: <'friendship date'>
            user: <User object>
        }
    ]
}
```



# Friend relationship

**URL:** https://api.twitch.tv/kraken/users/:userA/friends/:userB

**Method:** GET

**Authenticated:** true

**Schema:**
```javascript
{
    friends: <boolean>,
    status: <'sent_request' | 'friends' | etc>,
    user: <User object>
}
```

404 - No request | "userA does not have a friend request from userB."



# Add friend

**URL:** https://api.twitch.tv/kraken/users/:userA/friends/:userB

**Method:** PUT

**Authenticated:** true

**Schema:**
Success: 204 - No content



# Remove friend

**URL:** https://api.twitch.tv/kraken/users/:userA/friends/:userB

**Method:** DELETE

**Authenticated:** true

**Schema:**
Success: 204 - No content



# Get friend requests

**URL:** https://api.twitch.tv/kraken/users/:user/friends/requests

**Method:** GET

**Authenticated:** true

**Options:**
- *limit*: int, max length of array up to 100, default 25
- *cursor*: int, data offset timestamp in ns
- *offset*: int, data offset, default 0
- *direction*: string, ''DESC" or "ASC", default "DESC"

**Schema:**
```javascript
{
    _total: <int>,
    _cursor: <'timestamp in ns'>,
    _links: {
        self: <'url'>,
        next: <'url'>
    },
    requests: [
        {
            is_recommended: <boolean>
            is_stranger: <boolean>
            non_stranger_reason: <'mod' | null | etc>
            requested_at: <'timestamp'>,
            user: <User object>
        }
    ]
}
```



# Notification count

**URL:** https://api.twitch.tv/kraken/users/:user/friends/notifications

**Method:** GET

**Authenticated:** true

**Schema:**
```javascript
{
    count: <int>
}
```



# Clear notifications (Possibly)

**URL:** https://api.twitch.tv/kraken/users/:user/friends/notifications

**Method:** PUT

**Authenticated:** true

**Schema:**

Success: 204 - No content



# Recommended friend list

**URL:** https://api.twitch.tv/kraken/users/:user/friends/recommended

**Method:** GET

Authentication: true

Schema:
```javascript
{
    recommended: [
        {
            user: <User object>
        }
    ]
}
```



# Get list of user objects

Also useful to change an ID into a username instead of the hosts API.

**URL:** https://api.twitch.tv/api/friendships/users?ids=list,of,user,ids

**Method:** GET

**Authenticated:** false

**Schema:**
```javascript
{
    users: [
        {
            id: <int>,
            display_name: <'Username'>,
            login: <'username'>,
            logo: <'url'>,
            bio: <'user bio'>,
            profile_banner: <'url'>,
            profile_banner_background_color: <'#hexcolor'>
        }
    ]
}
```



# Get friend presence

**URL:** https://presence.twitch.tv/v1/friends

**Method:** GET

**Authenticated:** true

**Schema:**
```javascript
{
    data: [
        {
            availability: <'online' | 'offline' | 'idle'>
            index: <int>
            timestamp: <int in seconds>
            user_id: <int>
        }
    ]
}
```

**Comment by mavrick** [comment]
Ask and you shall receive @Fugiman ;)

Thanks @AlcaDesign

**Comment by TournyMasterBotCurse** [comment]
@AlcaDesign - Great info,

Can you describe the behavior required to get a User:Target friend relationship? Do you just need one at least one valid oauth token? (And make the comparison where the user is compared to the token you have?)

Can you also validate that the list of friends is intended to work without an oauth token? That seems like a bug, unless you're intending to have the list of friends comparison be public.

Example: I would expect this url to give 401 if I don't have a token, rather than a generic channel info
https://api.twitch.tv/api/friendships/users?ids=29795919,31723226 (Users are for nl_kripp and cobaltstreak)

**Comment by AlcaDesign** [comment]
@TournyMasterBotCurse I only looked at the network tab in the developers tools to get this data. I don't work for Twitch in any capacity, so anything I know comes from basic testing using the token that twitch made

![image](https://cloud.githubusercontent.com/assets/7132646/15103424/d2b1b120-1570-11e6-9177-00b68b1384ca.png)

And then test the token: https://api.twitch.tv/kraken?oauth_token= `token`

![image](https://cloud.githubusercontent.com/assets/7132646/15103435/fb70cff6-1570-11e6-853d-6b97054dc47a.png)

**Comment by TournyMasterBotCurse** [comment]
@AlcaDesign My mistake, good info none-the-less!

**Comment by grimmy** [comment]
fyi this seems to not work at all anymore.  In fact, if you do an oauth request with those scopes your oauth attemp fails with invalid scope.
