### ISSUE TITLE
Twitch Interactive Embed "Cannot read property 'appendChild' of null"

### ISSUE THREAD

**Issue by darkterra** [justintv/Twitch-API#581]
Hello,
I use since few days the Twitch API, specifically the section Interactive Video Embed to my website, but since yesterday I have an error. I have not change the code.

Here is the error " appendChild offi null".

When I comment all part concerning the player Twitch, my site works again.

Any ideas ?

**Comment by haleyyoung** [comment]
I'm having the same problem, but it appears it only happens if I load the embed API script a second time.

"Uncaught TypeError: Cannot read property 'appendChild' of null"

My code in the stacktrace `player = new Twitch.Player(playerId, options);`
v1.js in the stacktrace `e.appendChild(this._iframe)`

**Comment by darkterra** [comment]
Thank you @haleyyoung !
