### ISSUE TITLE
 How to Put Past Broadcasts Using the API twitch

### ISSUE THREAD

**Issue by zurdo2016** [justintv/Twitch-API#588]
Hi guy I need a help, I need to know how to put all transmissions of a channel Past Using the API twitch in a simple html , considering I'm an amateur , thanks for your help

**Comment by brentlapierre** [comment]
If I understood you correctly, you are asking how to fetch the past broadcasts of a channel. In order to do that, you must send a request to the /videos endpoint of a channel with a GET parameter of "broadcasts=true". Omit the GET parameter to get highlights instead.

Example: https://api.twitch.tv/kraken/channels/test_channel/videos?broadcasts=true

**Comment by zurdo2016** [comment]
I 'm sorry friend novice at this but I intereza the subject because I'm doing a project at school I Might Indicate how?

**Comment by DallasNChains** [comment]
For general questions about how to use the API, post on the [developer forums](https://discuss.dev.twitch.tv). This is for bugs or feature requests related to the API.
