### ISSUE TITLE
How could I get a list of broadcasters' streams?

### ISSUE THREAD

**Issue by skyline-123** [justintv/Twitch-API#655]
Excuse me. I wanna get information of many broadcasters. What should I do for getting the JSON file that including all the streams by only one  request?

**Comment by jwmalara** [comment]
See: https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#parameters

You can add feed the 'channel' parameter a comma separated list of channel names

Example: 
https://api.twitch.tv/kraken/streams?channel=lirik,richard_hammer

Before using this, however, I'd make sure this is available in V5. I personally haven't looked into it yet. I assume it works the same way but with ids instead of names.

**Comment by skyline-123** [comment]
@jwmalara The method is available, however, adding "client_id" query string variable breaks "/stream" requests if I feed the  'channel' parameter'. I changed it from '?' to '&' and finally made it. So, the twitch api really confused me a lot. Anyway, thank u so much.
